"""Add onboarding_completed to users

Revision ID: 9407f1ac89c9
Revises: 001_creator_tables
Create Date: 2025-11-12 18:16:08.846095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9407f1ac89c9'
down_revision: Union[str, Sequence[str], None] = '001_creator_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('generations_comfyui_prompt_id_key'), 'generations', type_='unique')
    op.drop_index(op.f('ix_generations_comfyui_prompt_id'), table_name='generations')
    op.create_index(op.f('ix_generations_comfyui_prompt_id'), 'generations', ['comfyui_prompt_id'], unique=True)
    op.drop_constraint(op.f('projects_public_slug_key'), 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_public_slug'), table_name='projects')
    op.create_index(op.f('ix_projects_public_slug'), 'projects', ['public_slug'], unique=True)
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('users_api_key_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('workflows_public_slug_key'), 'workflows', type_='unique')
    op.drop_index(op.f('ix_workflows_public_slug'), table_name='workflows')
    op.create_index(op.f('ix_workflows_public_slug'), 'workflows', ['public_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_public_slug'), table_name='workflows')
    op.create_index(op.f('ix_workflows_public_slug'), 'workflows', ['public_slug'], unique=False)
    op.create_unique_constraint(op.f('workflows_public_slug_key'), 'workflows', ['public_slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_api_key_key'), 'users', ['api_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'onboarding_completed')
    op.drop_index(op.f('ix_projects_public_slug'), table_name='projects')
    op.create_index(op.f('ix_projects_public_slug'), 'projects', ['public_slug'], unique=False)
    op.create_unique_constraint(op.f('projects_public_slug_key'), 'projects', ['public_slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_generations_comfyui_prompt_id'), table_name='generations')
    op.create_index(op.f('ix_generations_comfyui_prompt_id'), 'generations', ['comfyui_prompt_id'], unique=False)
    op.create_unique_constraint(op.f('generations_comfyui_prompt_id_key'), 'generations', ['comfyui_prompt_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
